"""WebSocket handler for real-time prediction streaming.

Provides WebSocket endpoints that push predictions to connected clients
as they are generated by the stream consumer.
"""

from __future__ import annotations

import asyncio
import json
import logging
from typing import Set

from fastapi import WebSocket, WebSocketDisconnect
from starlette.websockets import WebSocketState

logger = logging.getLogger(__name__)


class PredictionBroadcaster:
    """Manages WebSocket connections and broadcasts predictions.

    Thread-safe: predictions can be pushed from the consumer thread,
    and they'll be broadcast to all connected WebSocket clients.
    """

    def __init__(self):
        self._connections: Set[WebSocket] = set()
        self._machine_subscriptions: dict[str, Set[WebSocket]] = {}
        self._queue: asyncio.Queue | None = None

    @property
    def connection_count(self) -> int:
        return len(self._connections)

    async def connect(self, websocket: WebSocket, machine_id: str | None = None):
        """Accept a WebSocket connection."""
        await websocket.accept()
        self._connections.add(websocket)

        if machine_id:
            if machine_id not in self._machine_subscriptions:
                self._machine_subscriptions[machine_id] = set()
            self._machine_subscriptions[machine_id].add(websocket)

        logger.info(
            f"WebSocket connected ({self.connection_count} total)"
            + (f", subscribed to {machine_id}" if machine_id else "")
        )

    def disconnect(self, websocket: WebSocket, machine_id: str | None = None):
        """Remove a WebSocket connection."""
        self._connections.discard(websocket)

        if machine_id and machine_id in self._machine_subscriptions:
            self._machine_subscriptions[machine_id].discard(websocket)

        logger.info(f"WebSocket disconnected ({self.connection_count} total)")

    async def broadcast(self, prediction: dict):
        """Broadcast a prediction to all connected clients."""
        if not self._connections:
            return

        message = json.dumps(prediction, default=str)
        machine_id = prediction.get("machine_id")

        # Send to all general subscribers
        disconnected = set()
        for ws in self._connections:
            try:
                if ws.client_state == WebSocketState.CONNECTED:
                    await ws.send_text(message)
            except Exception:
                disconnected.add(ws)

        # Clean up disconnected
        for ws in disconnected:
            self._connections.discard(ws)

    async def broadcast_to_machine(self, prediction: dict):
        """Broadcast to clients subscribed to a specific machine."""
        machine_id = prediction.get("machine_id")
        if not machine_id or machine_id not in self._machine_subscriptions:
            return

        message = json.dumps(prediction, default=str)
        disconnected = set()

        for ws in self._machine_subscriptions[machine_id]:
            try:
                if ws.client_state == WebSocketState.CONNECTED:
                    await ws.send_text(message)
            except Exception:
                disconnected.add(ws)

        for ws in disconnected:
            self._machine_subscriptions[machine_id].discard(ws)

    def push_prediction(self, prediction: dict):
        """Thread-safe method to push a prediction for broadcasting.

        Called from the stream consumer thread. The prediction will be
        picked up by the async broadcast loop.
        """
        if self._queue:
            self._queue.put_nowait(prediction)

    async def start_broadcast_loop(self):
        """Async loop that reads from the queue and broadcasts."""
        self._queue = asyncio.Queue()
        while True:
            try:
                prediction = await asyncio.wait_for(
                    self._queue.get(), timeout=1.0
                )
                await self.broadcast(prediction)
                await self.broadcast_to_machine(prediction)
            except asyncio.TimeoutError:
                continue
            except Exception as e:
                logger.error(f"Broadcast error: {e}")


# Global broadcaster instance
broadcaster = PredictionBroadcaster()
